/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import ModelDTO.CamionDto;
import ModelDTO.CentreRecyclDto;
import ModelDTO.DemandeDto;
import ModelDTO.DetailsDemandeDto;
import ModelDTO.DetailsTourneeDto;
import ModelDTO.EmployeDto;
import ModelDTO.EntrepriseDto;
import ModelDTO.PoubelleDto;
import ModelDTO.TourneeDto;
import ModelDTO.TypeDechetDto;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import services.CamionServices;
import services.CentreRecyclServices;
import services.DemandeServices;
import services.DetailsDemandeServices;
import services.DetailsTourneeServices;
import services.EmployeServices;
import services.EntrepriseService;
import services.PoubelleService;
import services.TourneeService;
import services.TypeDechetService;

/**
 *
 * @author eddy.parisi
 */
public class AgentWindow extends javax.swing.JFrame {

    private List<TypeDechetDto> listTypesDechet;
    private List<EmployeDto> listEmployesLibre;
    private List<CamionDto> listCamions;
    private List<PoubelleDto> listPoubelles;
    private List<Integer> listIdPoubellesChoisient;
    private List<EntrepriseDto> listEntreprises;
    private List<CentreRecyclDto> listCentresRecycl;

    /**
     * Creates new form AgentWindow
     */
    public AgentWindow() {
        initComponents();
        listTypesDechet = new TypeDechetService().getAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogEntreprise = new javax.swing.JDialog();
        textfieldSiret = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textfieldRaisonSocial = new javax.swing.JTextField();
        textfieldNumero = new javax.swing.JTextField();
        textfieldRue = new javax.swing.JTextField();
        textfieldVille = new javax.swing.JTextField();
        textfieldCP = new javax.swing.JTextField();
        textfieldTel = new javax.swing.JTextField();
        textfieldContact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonValider = new javax.swing.JButton();
        ButtonRetour = new javax.swing.JButton();
        erreurDialog = new javax.swing.JDialog();
        errorDialogText = new javax.swing.JLabel();
        dialogTournee = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboboxTypesDechet = new javax.swing.JComboBox<>();
        comboboxCamions = new javax.swing.JComboBox<>();
        comboboxEmployes = new javax.swing.JComboBox<>();
        buttonValiderTournee = new javax.swing.JButton();
        buttonRetourTournee = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ui_listPoubelles = new javax.swing.JList<>();
        ui_textfieldOrdreTournee = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ui_comboboxRecycl = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ui_comboboxEntreprise = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ui_textfieldRemarque = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        ui_textfieldQuantite = new javax.swing.JTextField();
        butonAddTournee = new javax.swing.JButton();
        buttonAddEntreprise = new javax.swing.JButton();

        dialogEntreprise.setSize(new java.awt.Dimension(406, 368));

        jLabel1.setText("Siret :");

        jLabel2.setText("Raison sociale :");

        jLabel3.setText("Numéro :");

        jLabel4.setText("Rue :");

        jLabel5.setText("Ville :");

        jLabel6.setText("Code postal :");

        jLabel7.setText("Téléphone :");

        jLabel8.setText("Contact :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Ajouter une entreprise");

        buttonValider.setText("Valider");
        buttonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderActionPerformed(evt);
            }
        });

        ButtonRetour.setText("Retour");
        ButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogEntrepriseLayout = new javax.swing.GroupLayout(dialogEntreprise.getContentPane());
        dialogEntreprise.getContentPane().setLayout(dialogEntrepriseLayout);
        dialogEntrepriseLayout.setHorizontalGroup(
            dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEntrepriseLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogEntrepriseLayout.createSequentialGroup()
                        .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldRaisonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldRue, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldSiret, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogEntrepriseLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogEntrepriseLayout.createSequentialGroup()
                        .addComponent(buttonValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetour)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        dialogEntrepriseLayout.setVerticalGroup(
            dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEntrepriseLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldSiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfieldRaisonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textfieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textfieldRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textfieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textfieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textfieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(dialogEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonValider)
                    .addComponent(ButtonRetour))
                .addGap(25, 25, 25))
        );

        erreurDialog.setTitle("Erreur");
        erreurDialog.setSize(new java.awt.Dimension(581, 140));

        javax.swing.GroupLayout erreurDialogLayout = new javax.swing.GroupLayout(erreurDialog.getContentPane());
        erreurDialog.getContentPane().setLayout(erreurDialogLayout);
        erreurDialogLayout.setHorizontalGroup(
            erreurDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erreurDialogLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(errorDialogText, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        erreurDialogLayout.setVerticalGroup(
            erreurDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erreurDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(errorDialogText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        dialogTournee.setPreferredSize(new java.awt.Dimension(400, 575));
        dialogTournee.setSize(new java.awt.Dimension(400, 575));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Ajouter une tournée");

        jLabel11.setText("Type de déchet :");

        jLabel12.setText("Camion :");
        jLabel12.setToolTipText("");

        jLabel13.setText("Employé :");

        comboboxTypesDechet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxTypesDechetItemStateChanged(evt);
            }
        });

        buttonValiderTournee.setText("Valider");
        buttonValiderTournee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderTourneeActionPerformed(evt);
            }
        });

        buttonRetourTournee.setText("Retour");
        buttonRetourTournee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourTourneeActionPerformed(evt);
            }
        });

        ui_listPoubelles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ui_listPoubelles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ui_listPoubellesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ui_listPoubelles);

        ui_textfieldOrdreTournee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel14.setText("RECYCL :");

        jLabel15.setText("Entreprise :");

        jLabel16.setText("Remarque :");

        label1.setText("Quantité :");

        javax.swing.GroupLayout dialogTourneeLayout = new javax.swing.GroupLayout(dialogTournee.getContentPane());
        dialogTournee.getContentPane().setLayout(dialogTourneeLayout);
        dialogTourneeLayout.setHorizontalGroup(
            dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTourneeLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogTourneeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogTourneeLayout.createSequentialGroup()
                        .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ui_comboboxEntreprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ui_comboboxRecycl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ui_textfieldRemarque)
                            .addComponent(ui_textfieldQuantite, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(ui_textfieldOrdreTournee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogTourneeLayout.createSequentialGroup()
                        .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboboxTypesDechet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboboxCamions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboboxEmployes, 0, 161, Short.MAX_VALUE))
                            .addGroup(dialogTourneeLayout.createSequentialGroup()
                                .addComponent(buttonValiderTournee)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRetourTournee)))))
                .addGap(80, 80, 80))
        );
        dialogTourneeLayout.setVerticalGroup(
            dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTourneeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboboxTypesDechet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboboxCamions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(comboboxEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ui_textfieldOrdreTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ui_comboboxRecycl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ui_comboboxEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ui_textfieldRemarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ui_textfieldQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(dialogTourneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonValiderTournee)
                    .addComponent(buttonRetourTournee))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonAddTournee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butonAddTournee.setText("Ajouter une tournée");
        butonAddTournee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAddTourneeActionPerformed(evt);
            }
        });

        buttonAddEntreprise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAddEntreprise.setText("Ajouter une entreprise");
        buttonAddEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEntrepriseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAddEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonAddTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(butonAddTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEntrepriseActionPerformed
        dialogEntreprise.setVisible(true);
    }//GEN-LAST:event_buttonAddEntrepriseActionPerformed

    private void buttonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderActionPerformed
        // Check errors
        if (isError()) {
            errorDialogText.setText("Tous les champs doivent être renseignés");
        } else {
            //add si pas d'erreur
            EntrepriseDto newEntreprise = getEntreprise();
            reset();
            if (new EntrepriseService().create(newEntreprise)) {
                dialogEntreprise.setVisible(false);
            } else {
                errorDialogText.setText("Erreur veuillez contacter l'administrateur.");
            }
        }
        if (!errorDialogText.getText().equals("")) {
            erreurDialog.setVisible(true);
        }
    }//GEN-LAST:event_buttonValiderActionPerformed

    private void ButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetourActionPerformed
        //reset
        reset();
        dialogEntreprise.setVisible(false);
    }//GEN-LAST:event_ButtonRetourActionPerformed

    private void butonAddTourneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAddTourneeActionPerformed
        // intialisation des variables
        listIdPoubellesChoisient = new ArrayList<>();
        listEntreprises = new ArrayList<>();
        listCentresRecycl = new ArrayList<>();
        ui_textfieldRemarque.setText("");
        ui_textfieldQuantite.setText("");
        errorDialogText.setText("");
        // Les types de dechet
        listTypesDechet = new TypeDechetService().getAll();
        Stream<String> streamType = listTypesDechet.stream().map(type -> type.getLibelle());
        comboboxTypesDechet.setModel(new DefaultComboBoxModel(streamType.toArray()));
        // Les employes libres
        listEmployesLibre = new EmployeServices().getAllChauffeursLibres();
        Stream<String> streamEmp = listEmployesLibre.stream().map(type -> type.toString());
        Stream<String> streamEmpCopy = listEmployesLibre.stream().map(type -> type.toString());
        if (streamEmp.count() == 0) {
            errorDialogText.setText("Il n'y a pas d'employé de libre. Vous ne pourrez pas créer de tournée.");
        } else {
            comboboxEmployes.setModel(new DefaultComboBoxModel(streamEmpCopy.toArray()));
        }
        // Les camions adéquat au type de déchets
        listCamions = getCamionFromLibelleTypeDechet(comboboxTypesDechet.getItemAt(0));
        Stream<String> streamCamion = listCamions.stream().map(camion -> camion.toString());
        comboboxCamions.setModel(new DefaultComboBoxModel(streamCamion.toArray()));
        // Les poubelles adéquat au type de déchets
        listPoubelles = new PoubelleService().getAll_AVidee_libelleTypeDechet(comboboxTypesDechet.getItemAt(0));
        Stream<String> streamPoubelle = listPoubelles.stream().map(poubelle -> poubelle.toString());
        ui_listPoubelles.setListData(streamPoubelle.toArray(String[]::new));
        // Les entreprises
        listEntreprises = new EntrepriseService().getAll();
        Stream<String> streamEntreprise = listEntreprises.stream().map(entreprise -> entreprise.getShortDecription());
        ui_comboboxEntreprise.setModel(new DefaultComboBoxModel(streamEntreprise.toArray()));
        // Les Centres Recycl
        listCentresRecycl = new CentreRecyclServices().getAll();
        Stream<String> streamCentreRecycl = listCentresRecycl.stream().map(centreRecycl -> centreRecycl.getVille());
        ui_comboboxRecycl.setModel(new DefaultComboBoxModel(streamCentreRecycl.toArray()));

        dialogTournee.setVisible(true);
        if (!errorDialogText.getText().equals("")) {
            erreurDialog.setVisible(true);
        }
    }//GEN-LAST:event_butonAddTourneeActionPerformed

    private void ui_listPoubellesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ui_listPoubellesMouseClicked
        JList list = (JList) evt.getSource();
        int indexPoubelleClicked = list.locationToIndex(evt.getPoint());
        int idPoubelle = Integer.parseInt(list.getModel().getElementAt(indexPoubelleClicked).toString().substring(0, 1));
        if (listIdPoubellesChoisient.contains(idPoubelle)) {
            listIdPoubellesChoisient.remove((Object) idPoubelle);
        } else {
            listIdPoubellesChoisient.add(idPoubelle);
        }
        ui_textfieldOrdreTournee.setText("Ordre de la tournée : " + listIdPoubellesChoisient.toString());
    }//GEN-LAST:event_ui_listPoubellesMouseClicked

    private void buttonRetourTourneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourTourneeActionPerformed
        listIdPoubellesChoisient = new ArrayList<>();
        listEntreprises = new ArrayList<>();
        listCentresRecycl = new ArrayList<>();
        ui_textfieldRemarque.setText("");
        ui_textfieldQuantite.setText("");
        errorDialogText.setText("");
        dialogTournee.setVisible(false);
    }//GEN-LAST:event_buttonRetourTourneeActionPerformed

    private void buttonValiderTourneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderTourneeActionPerformed
        // Recover data
        String libelleTypesDechet = comboboxTypesDechet.getSelectedItem().toString();
        String stringCamion = comboboxCamions.getSelectedItem().toString();
        String stringEmploye = comboboxEmployes.getSelectedItem().toString();
        String remarque = ui_textfieldRemarque.getText();
        String stringEntreprise = ui_comboboxEntreprise.getSelectedItem().toString();
        String stringRecycl = ui_comboboxRecycl.getSelectedItem().toString();
        int quantité = Integer.parseInt(ui_textfieldQuantite.getText());
        // Recover formattedData
        TypeDechetDto td = listTypesDechet.stream().reduce(
                null,
                (_tdKepped, _td) -> _td.getLibelle().equals(libelleTypesDechet) ? _td : _tdKepped
        );
        CamionDto camion = listCamions.stream().reduce(
                null,
                (_camionKepped, _camion) -> _camion.toString().equals(stringCamion) ? _camion : _camionKepped
        );
        EmployeDto emp = listEmployesLibre.stream().reduce(
                null,
                (_empKepped, _emp) -> _emp.toString().equals(stringEmploye) ? _emp : _empKepped
        );
        EntrepriseDto entreprise = listEntreprises.stream().reduce(
                null,
                (_entrepriseKepped, _entreprise) -> _entreprise.getShortDecription().equals(stringEntreprise) ? _entreprise : _entrepriseKepped
        );
        CentreRecyclDto centre = listCentresRecycl.stream().reduce(
                null,
                (_centreKepped, _centre) -> _centre.getVille().equals(stringRecycl) ? _centre : _centreKepped
        );
        // Send data
        sendData(td, camion, emp, entreprise, centre, remarque, quantité);
        // Reset
        dialogTournee.setVisible(false);
    }//GEN-LAST:event_buttonValiderTourneeActionPerformed

    private void comboboxTypesDechetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxTypesDechetItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            // Initialisation des vars
            listIdPoubellesChoisient = new ArrayList<>();
            ui_textfieldOrdreTournee.setText("Ordre de la tournée : " + listIdPoubellesChoisient.toString());
            String libelleTypeDechet = evt.getItem().toString();
            // Redefinition des camions
            listCamions = getCamionFromLibelleTypeDechet(libelleTypeDechet);
            Stream<String> streamCamion = listCamions.stream().map(camion -> camion.toString());
            comboboxCamions.setModel(new DefaultComboBoxModel(streamCamion.toArray()));
            // Redefinition des poubelles
            listPoubelles = new PoubelleService().getAll_AVidee_libelleTypeDechet(libelleTypeDechet);
            Stream<String> streamPoubelle = listPoubelles.stream().map(poubelle -> poubelle.toString());
            ui_listPoubelles.setListData(streamPoubelle.toArray(String[]::new));
        }
    }//GEN-LAST:event_comboboxTypesDechetItemStateChanged

    private Boolean isError() {
        Boolean _isError = false;

        if (textfieldCP.getText().equals("")) {
            textfieldCP.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldContact.getText().equals("")) {
            textfieldContact.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldNumero.getText().equals("")) {
            textfieldNumero.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldRaisonSocial.getText().equals("")) {
            textfieldRaisonSocial.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldRue.getText().equals("")) {
            textfieldRue.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldSiret.getText().equals("")) {
            textfieldSiret.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldTel.getText().equals("")) {
            textfieldTel.setBackground(Color.red);
            _isError = true;
        }
        if (textfieldVille.getText().equals("")) {
            textfieldVille.setBackground(Color.red);
            _isError = true;
        }

        return _isError;
    }

    private void reset() {
        textfieldCP.setText("");
        textfieldContact.setText("");
        textfieldNumero.setText("");
        textfieldRaisonSocial.setText("");
        textfieldRue.setText("");
        textfieldSiret.setText("");
        textfieldTel.setText("");
        textfieldVille.setText("");
        textfieldCP.setBackground(Color.WHITE);
        textfieldContact.setBackground(Color.WHITE);
        textfieldNumero.setBackground(Color.WHITE);
        textfieldRaisonSocial.setBackground(Color.WHITE);
        textfieldRue.setBackground(Color.WHITE);
        textfieldSiret.setBackground(Color.WHITE);
        textfieldTel.setBackground(Color.WHITE);
        textfieldVille.setBackground(Color.WHITE);
        errorDialogText.setText("");
    }

    private EntrepriseDto getEntreprise() {
        return new EntrepriseDto(
                Long.parseLong(textfieldSiret.getText()),
                textfieldRaisonSocial.getText(),
                Integer.parseInt(textfieldNumero.getText()),
                textfieldRue.getText(),
                textfieldVille.getText(),
                Integer.parseInt(textfieldCP.getText()),
                Integer.parseInt(textfieldTel.getText()),
                textfieldContact.getText()
        );
    }

    private List<CamionDto> getCamionFromLibelleTypeDechet(String libelle) {
        List<TypeDechetDto> typesDechet = listTypesDechet.stream().filter(
                type -> type.getLibelle().equals(libelle)).collect(Collectors.toList());
        TypeDechetDto typeDechet = typesDechet.get(0);

        return new CamionServices().getAllFromIdTypeDechet(typeDechet.getId());
    }

    private void sendData(TypeDechetDto td, CamionDto camion, EmployeDto emp, EntrepriseDto entreprise, CentreRecyclDto centre, String remarque, int quantité) {
        // Ajouter dans tournee
        TourneeDto tourneeDto = new TourneeDto(1, new Date(), emp, camion);
        tourneeDto = new TourneeService().create(tourneeDto);
        // Ajouter dans demande
        DemandeDto demandeDto = new DemandeDto(1, remarque, new Date(), new Date(), entreprise, centre);
        demandeDto = new DemandeServices().create(demandeDto);
        // Aour chaque idPoubelle
        DetailsDemandeServices detailsDemandeServices = new DetailsDemandeServices();
        DetailsTourneeServices detailsTourneeServices = new DetailsTourneeServices();
        for (int i = 0; i < listIdPoubellesChoisient.size(); i++) {
            int idPoubelle = listIdPoubellesChoisient.get(i);
            DetailsDemandeDto detailsDemandeDto = new DetailsDemandeDto(demandeDto.getId(), td, quantité, new PoubelleDto());
            detailsDemandeServices.create(detailsDemandeDto, idPoubelle);
            DetailsTourneeDto detailsTourneeDto = new DetailsTourneeDto(tourneeDto, detailsDemandeDto, td);
            detailsTourneeServices.create(detailsTourneeDto);
        }
    }

    public List<TypeDechetDto> getListTypesDechet() {
        return listTypesDechet;
    }

    public void setListTypesDechet(List<TypeDechetDto> listTypesDechet) {
        this.listTypesDechet = listTypesDechet;
    }

    public List<EmployeDto> getListEmployesLibre() {
        return listEmployesLibre;
    }

    public void setListEmployesLibre(List<EmployeDto> listEmployesLibre) {
        this.listEmployesLibre = listEmployesLibre;
    }

    public List<CamionDto> getListCamions() {
        return listCamions;
    }

    public List<PoubelleDto> getListPoubelles() {
        return listPoubelles;
    }

    public void setListPoubelles(List<PoubelleDto> listPoubelles) {
        this.listPoubelles = listPoubelles;
    }

    public void setListCamions(List<CamionDto> listCamions) {
        this.listCamions = listCamions;
    }

    public List<Integer> getListIdPoubellesChoisient() {
        return listIdPoubellesChoisient;
    }

    public void setListIdPoubellesChoisient(List<Integer> listIdPoubellesChoisient) {
        this.listIdPoubellesChoisient = listIdPoubellesChoisient;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRetour;
    private javax.swing.JButton butonAddTournee;
    private javax.swing.JButton buttonAddEntreprise;
    private javax.swing.JButton buttonRetourTournee;
    private javax.swing.JButton buttonValider;
    private javax.swing.JButton buttonValiderTournee;
    private javax.swing.JComboBox<String> comboboxCamions;
    private javax.swing.JComboBox<String> comboboxEmployes;
    private javax.swing.JComboBox<String> comboboxTypesDechet;
    private javax.swing.JDialog dialogEntreprise;
    private javax.swing.JDialog dialogTournee;
    private javax.swing.JDialog erreurDialog;
    private javax.swing.JLabel errorDialogText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTextField textfieldCP;
    private javax.swing.JTextField textfieldContact;
    private javax.swing.JTextField textfieldNumero;
    private javax.swing.JTextField textfieldRaisonSocial;
    private javax.swing.JTextField textfieldRue;
    private javax.swing.JTextField textfieldSiret;
    private javax.swing.JTextField textfieldTel;
    private javax.swing.JTextField textfieldVille;
    private javax.swing.JComboBox<String> ui_comboboxEntreprise;
    private javax.swing.JComboBox<String> ui_comboboxRecycl;
    private javax.swing.JList<String> ui_listPoubelles;
    private javax.swing.JLabel ui_textfieldOrdreTournee;
    private javax.swing.JTextField ui_textfieldQuantite;
    private javax.swing.JTextField ui_textfieldRemarque;
    // End of variables declaration//GEN-END:variables
}
