/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import ModelDTO.DemandeDto;
import ModelDTO.DetailsTourneeDto;
import ModelDTO.TourneeDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import services.DemandeServices;
import services.TourneeService;

/**
 *
 * @author eddy.parisi
 */
public class EmployeWimdow extends javax.swing.JFrame {

    private List<TourneeDto> listTournees;
    
    /**
     * Creates new form EmployeWimdow
     * @param idEmploye
     */
    public EmployeWimdow(int idEmploye) {
        initComponents();
        listTournees = new TourneeService().getAllFromIdEmploye(idEmploye);
        String ordonateListItemHTML = getOrdonateListItemHTML();
        ui_textfieldTournéeShow.setText(String.valueOf(
                ""
                + "<html>"
                + "<h2>Force et honneur pour vos tournées !</h2>"
                + ordonateListItemHTML
                + "</html>"
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_textfieldTournéeShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ui_textfieldTournéeShow, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ui_textfieldTournéeShow, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getOrdonateListItemHTML() {
        // Recupération
        String listHTML = "";
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd-MM-yyyy");
        DemandeServices demandeService = new DemandeServices();
        for (int i = 0; i < listTournees.size(); i++) {
            // Pour chaque tournee on va récupérer la liste des details des tournees     
            TourneeDto tournee = listTournees.get(i);
            List<DetailsTourneeDto> listDetailsTournee = tournee.getDetailsTourneeList();
            // Affichage
            listHTML += i == 0 ? ("<h3>-- Tournée du " + dateFormatter.format(tournee.getDate()) + " --</h3><ol>") : ("</ol><h3>-- Tournée du " + dateFormatter.format(tournee.getDate()) + " --</h3><ol>");
            for (int j = 0; j < listDetailsTournee.size(); j++) {
                // Pour chaque details de tournee on va recuperer la demande
                DetailsTourneeDto detailsTournee = listDetailsTournee.get(j);
                DemandeDto demande = demandeService.getOneById(detailsTournee.getDetailsDemande().getIdDemande());
                
                // Afin de creer l'element
                listHTML += ("<li>" + demande.toString() + "</li>");
            }
        }
        
        listHTML += "</ol>";
        return listHTML;
    }

    public List<TourneeDto> getListTournees() {
        return listTournees;
    }

    public void setListTournees(List<TourneeDto> listTournees) {
        this.listTournees = listTournees;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ui_textfieldTournéeShow;
    // End of variables declaration//GEN-END:variables
}
