/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author eddy.parisi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form loginPannel
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannelLogin = new javax.swing.JPanel();
        textfieldLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfieldPwd = new javax.swing.JTextField();
        buttonConnecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pannelLogin.setBackground(new java.awt.Color(255, 255, 255));

        textfieldLogin.setToolTipText("");

        jLabel1.setText("Login");

        jLabel2.setText("Mot de passe");

        buttonConnecter.setText("Se connecter");
        buttonConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelLoginLayout = new javax.swing.GroupLayout(pannelLogin);
        pannelLogin.setLayout(pannelLoginLayout);
        pannelLoginLayout.setHorizontalGroup(
            pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(pannelLoginLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(buttonConnecter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannelLoginLayout.setVerticalGroup(
            pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelLoginLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(pannelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(buttonConnecter)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnecterActionPerformed
        HttpURLConnection connection = null;
        Map<String, String> roles = new HashMap<>();
        roles.put("E", "Employe");
        roles.put("R", "Responsable");
        roles.put("A", "Agent");
        roles.put("N", "PDG");
        roles.put("M", "RH");//M pour N-1 ;-)

        //reset default parameter
        textfieldLogin.setBackground(Color.WHITE);
        textfieldPwd.setBackground(Color.WHITE);

        // Recover user data
        String login = textfieldLogin.getText();
        String pwd = textfieldPwd.getText();

        // Send data to the backend
        try {
            // Create connection
            URL url = new URL("");
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type",
                "application/x-www-form-urlencoded");

            // Send request
            DataOutputStream wr = new DataOutputStream(
                connection.getOutputStream());
            wr.writeBytes("login=" + login + "&pwd=" + pwd);
            wr.flush();
            wr.close();

            // Get response
            InputStream is = connection.getInputStream();
            BufferedReader rd = new BufferedReader(new InputStreamReader(is));
            String line;
            StringBuffer response = new StringBuffer();
            while ((line = rd.readLine()) != null) {
                response.append(line);
                response.append('\r');
            }
            rd.close();
            String res = response.toString();

            // Print response
            System.out.println("reponse :\r" + res);

            // Recover code
            if (true) {
                // If code 200 recover role with the first letter of login
                String letter = login.substring(0, 1);
                String role = roles.get(letter);
                //Hide and Show the right pannel"Employe");
            pannelLogin.setVisible(false);
            switch(role) {
                case "Employe":
                //show employePannel
                break;
                case "Responsable":
                //show responsablePannel
                break;
                case "Agent":
                //show agentPannel
                break;
                case "PDG":
                //show pdgPannel
                break;
                case "RH":
                //show rhPannel
                break;
            }
        } else {
            //else show error
            textfieldLogin.setBackground(Color.red);
            textfieldPwd.setBackground(Color.red);
        }
        } catch (IOException e) {
        }

        textfieldLogin.setText(textfieldLogin.getBackground().toString());
        //pannelLogin.setVisible(false);
    }//GEN-LAST:event_buttonConnecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pannelLogin;
    private javax.swing.JTextField textfieldLogin;
    private javax.swing.JTextField textfieldPwd;
    // End of variables declaration//GEN-END:variables
}
