/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import ModelDTO.TourneeDto;
import services.TourneeService;
import java.util.List;

/**
 *
 * @author morga
 */
public class ResponsableWindow extends javax.swing.JFrame {

    /**
     * Creates new form responsableWindow
     */
    public ResponsableWindow() {
        initComponents();
        List<TourneeDto> tourneeList =  new TourneeService().getTournees();
        // mettre la liste triée par date dans le jtable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeRadio = new javax.swing.ButtonGroup();
        radioHier = new javax.swing.JRadioButton();
        radioAjd = new javax.swing.JRadioButton();
        radioDemain = new javax.swing.JRadioButton();
        editDate = new javax.swing.JTextField();
        jTable1 = new javax.swing.JTable();
        radioChoix = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        groupeRadio.add(radioHier);
        radioHier.setText("Hier");
        radioHier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHierActionPerformed(evt);
            }
        });

        groupeRadio.add(radioAjd);
        radioAjd.setSelected(true);
        radioAjd.setText("aujourd'hui");
        radioAjd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAjdActionPerformed(evt);
            }
        });

        groupeRadio.add(radioDemain);
        radioDemain.setText("demain");
        radioDemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDemainActionPerformed(evt);
            }
        });

        editDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        groupeRadio.add(radioChoix);
        radioChoix.setText("choisir par date");
        radioChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChoixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioHier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioAjd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDemain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioChoix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHier)
                    .addComponent(radioAjd)
                    .addComponent(radioDemain)
                    .addComponent(editDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioChoix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioHierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHierActionPerformed

    private void radioAjdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAjdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAjdActionPerformed

    private void radioDemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDemainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDemainActionPerformed

    private void editDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDateActionPerformed

    private void radioChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChoixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioChoixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResponsableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResponsableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResponsableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResponsableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResponsableWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editDate;
    private javax.swing.ButtonGroup groupeRadio;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioAjd;
    private javax.swing.JRadioButton radioChoix;
    private javax.swing.JRadioButton radioDemain;
    private javax.swing.JRadioButton radioHier;
    // End of variables declaration//GEN-END:variables
}
